<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="bilgimetni.aspx.cs" Inherits="odevv.bilgimetni" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>KULLANIM KOŞULLARI VE HAKLAR </h1>
            <h2 class="altbaslik" style="box-sizing: border-box; margin: 20px 0px 10px; padding: 0px !important; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 600; font-stretch: inherit; font-size: 17px !important; line-height: 1.2 !important; font-family: inherit; vertical-align: baseline; outline: 0px; transition: all 0.2s ease-in-out 0s; text-align: left; color: rgb(72, 72, 72); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Kişisel Veri Sahibi Olarak Müşterilerin Hakları:</h2>
            <p class="klasik" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: 1.6 !important; font-family: Helvetica, &quot; open sans&quot; , arial, tahoma, sans-serif; vertical-align: baseline; outline: 0px; transition: all 0.2s ease-in-out 0s; color: rgb(72, 72, 72); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
                Kanun’un 11. maddesi uyarınca veri sahipleri; (i) kendileri ile ilgili kişisel veri işlenip işlenmediğini öğrenme, (ii) kişisel verileri işlenmişse buna ilişkin bilgi talep etme, (iii) kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme, (iv) yurt içinde veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri bilme, (v) kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, (vi) Kanun ve ilgili diğer kanun hükümlerine uygun olarak işlenmiş olmasına rağmen, işlenmesini gerektiren sebeplerin ortadan kalkması hâlinde kişisel verilerin silinmesini veya yok edilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, (vii) işlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir sonucun 
                  ortaya çıkmasına itiraz etme ve (viii) kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması hâlinde zararın giderilmesini talep etme haklarına sahiptir.
            </p>
            <p class="klasik" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: 1.6 !important; font-family: Helvetica, &quot; open sans&quot; , arial, tahoma, sans-serif; vertical-align: baseline; outline: 0px; transition: all 0.2s ease-in-out 0s; color: rgb(72, 72, 72); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
                Söz konusu hakların kullanımına ilişkin talepler, kişisel veri sahipleri tarafından
            </p>
            <br />
            Müşterilere Ait Kişisel Verilerin İşlenme Amacı:
Müşterilere ait kişisel veriler, Hepsiburada tarafından sunulan ürün ve hizmetlerden ilgili kişileri faydalandırmak için gerekli çalışmaların iş birimleri tarafından yapılması ve ilgili iş süreçlerinin yürütülmesi, Hepsiburada tarafından yürütülen ticari faaliyetlerin gerçekleştirilmesi için ilgili iş birimleri tarafından gerekli çalışmaların yapılması ve buna bağlı iş süreçlerinin yürütülmesi, Hepsiburada’nın ticari ve/veya iş stratejilerinin planlanması ve icrası, Hepsiburada’nın ve Hepsiburada ile iş ilişkisi içerisinde olan ilgili kişilerin hukuki, teknik ve ticari iş güvenliğinin temini de dahil olmak üzere Kanun’un 5. ve 6. maddelerinde belirtilen kişisel veri işleme şartları ve amaçları çerçevesinde işlenmektedir. Kişisel verilerin işlenmesine ilişkin detaylı bilgilere Hepsiburada Tarafından 6698 sayılı Kanun Kapsamında Kişisel Verilerin İşlenmesi ve Korunmasına İlişkin Politika’dan ulaşılabilecektir.
            
              Bölüm 3 – Madde IV altında belirtilen amaçlarla ve buradaki usule uygun olarak işlenmektedir. Buna göre kişisel veriler; müşterilere yönelik kampanyaların oluşturulması, Hepsiburada iş ortakları tarafından Hepsiburada müşterilerine Hepsiburada’da kullanabilecekleri özel fırsatların sunulması, çapraz satış yapılması, hedef kitle belirlenmesi, Müşteri hareketlerinin takip edilerek kullanıcı deneyimini arttırıcı faaliyetlerin yürütülmesi, Hepsiburada’ya ait internet sitesi ile mobil uygulamanın işleyişinin geliştirilmesi ve Müşteri ihtiyaçlarına göre kişiselleştirilmesi, doğrudan ve doğrudan olmayan pazarlama, kişiye özel pazarlama ve yeniden pazarlama faaliyetlerinin yürütülmesi, kişiye özel segmentasyon, hedefleme, analiz ve şirket içi raporlama faaliyetlerinin yürütülmesi, pazar araştırmaları, müşteri memnuniyeti aktivitelerinin planlanması ve icrası, Hepsiburada’nın sunduğu ürün ve hizmetlerin ilgili kişilerin beğeni, kullanım alışkanlıkları ve ihtiyaçlarına göre özelleştirilerek ilgili kişilere önerilmesi ve tanıtılması ile müşteri ilişkileri yönetimi süreçlerinin planlanması ve icrası amaçları da dahil olmak üzere genel anlamda Hepsiburada’nın ürün ve/veya hizmetlerinin satış ve pazarlama süreçlerinin planlanması ve icrası, Hepsiburada’nın sunduğu ürün ve/veya hizmetlere bağlılık oluşturulması ve/veya arttırılması süreçlerinin planlanması ve icrası kapsamında Müşteri’nin vereceği onayı doğrultusunda işlenebilecek ve bu amaçlara yönelik olarak Aydınlatma Metni’nde belirtilen taraflarla paylaşılabilecektir.<br />
            <br />
            Aydınlatma Metni’nin Amacı ve Şirketimizin Veri Sorumlusu Konumu:
Şirketimiz D-Market Elektronik Hizmetler ve Ticaret A.Ş. (“Hepsiburada” ve/veya “Şirket”), müşterilere ilişkin kişisel veriler bakımından 6698 sayılı Kişisel Verilerin Korunması Kanunu (“Kanun”) kapsamında “veri sorumlusu” sıfatına sahip olup işbu Aydınlatma Metni ile söz konusu Kanun uyarınca müşterilerin Hepsiburada tarafından gerçekleştirilen kişisel veri işleme faaliyetleri hakkında aydınlatılması hedeflenmektedir.
              <br />
        </div>
        <%--<asp:Button Text="TAMAM" runat="server" OnClick="Unnamed1_Click" />--%>
    </form>
</body>
</html>
